version: '3.8'

services:
  pdf-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - LOG_LEVEL=debug
    volumes:
      - ../src:/app/src
      - ../temp:/app/temp
      - ../logs:/app/logs
    restart: unless-stopped
